name = "leetcode-express-server"
main = "dist/index.js"
compatibility_date = "2024-01-01"

[env.production.vars]
UPSTASH_REDIS_REST_URL = "your_upstash_url_here"
UPSTASH_REDIS_REST_TOKEN = "your_upstash_token_here"
